version: '3'

services:
  db:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=db_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql
      - db_data:/var/lib/postgresql/data
  api:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  db:
  db_data: