# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# Workflow for the backEnd
jobs:
  back-end_batch:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back-end
    steps:
      - uses: actions/checkout@v2
      - name: Back-end bash -> Install modules
        run: npm install
      - name: Back-end bash -> Run ESLint
        run: npm run lint:fix
      - name: Back-end bash -> Run Jest
        run: npm run test:cov
  
  front-end_batch:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front-end
    steps:
      - uses: actions/checkout@v2
      - name: Front-end bash -> Install modules
        run: npm install
      - name: Front-end bash -> Run ESLint
        run: npm run lint:fix
      - name: Front-end bash -> Run Jest
        run: npm run test:cov